import burger from "../../../images/burger.png";
import sandwich from "../../../images/sandviches.png";
import shurama from "../../../images/bigburger.png";
import lavash from "../../../images/lavash.png";
export const data = [
  {
    title: "Лаваш",
    products: [
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 22000,
        available: true,
        discount: false,
        img: lavash,
        options: [
          {
            type: "radio",
            label: "Объем",
            properties: [
              {
                name: "Мини",
                id: 1,
                price: 22000,
              },
              {
                name: "Большой",
                id: 2,
                price: 28000,
              },
            ],
          },
          {
            type: "checkbox",
            label: "Добавки",
            properties: [
              {
                name: "Классик",
                id: 3,
                price: 3000,
              },
              {
                name: "Классик",
                id: 4,
                price: 3000,
              },
            ],
          },
        ],
      },
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: false,
        discount: false,
        img: lavash,
      },
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: lavash,
      },
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: "12",
        img: lavash,
      },
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: lavash,
      },
      {
        food_type: "lavash",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: lavash,
      },
    ],
  },
  {
    title: "Бургеры",
    products: [
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
      {
        food_type: "burger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: burger,
      },
    ],
  },
  {
    title: "Sandwich",
    products: [
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
      {
        food_type: "cheeseBurger",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: sandwich,
      },
    ],
  },
  {
    title: "Шаурма",
    products: [
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
      {
        food_type: "shaurma",
        name: "Комбо 1",
        description: "Мясной лаваш, фри, кола разлив и кетчуп",
        price: 39000,
        available: true,
        discount: false,
        img: shurama,
      },
    ],
  },
];
